export interface AddRequisition {
  requisitionID: string,
  requisitionCode: string,
  potentialNumber: string,
  complexity: string,
  requisitionDate: string,
  deadlineDate: string,
  clientName: string,
  clientCountreyID: string,
  projectType: string,
  salesPersonUserID: string,
  projectManagerID: string,
  requisitionStatus: number,
  expectedStartDate: string,
  estimatedBudget: number,
  departmentID: string,
  currencyID: string,
  projectDescription: string,
  jobDescription: string
  duration: number,
  durationUnits: string,
  shiftTimings: string,
  noOfResources: number,
  openPositions: number,
  keyDescription: string,
  preferredEducation: string,
  minExperience: number,
  maxExperience: number,
  jdFileName: string,
  skillID: string,
  mandatory: string,
  experience: number,
  comments: string,
  partnerID: string
}

